### PR TITLE
use iso code instead of country name in countries.csv;

### PR DESCRIPTION
**Pull request by ItzBubschki**
This implements the changes proposed in #13 and fixes the issue #20 as a side-effect
Also added the ability to submit a Locale that is used for the final country name

As a part of this i updated the names for the countries used in data/countries.csv to the ones that are used by jdk 21
Since these names are never directly returned, this change should not affect users and is merely an aesthetic improvement.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks a lot!
I will review this as soon as possible. :-)

**Review by nicolas-raoul — COMMENTED** [review]
Unit tests fail when I build, any idea what might be the issue?
```
org.junit.ComparisonFailure: expected:<T[ürkiye]> but was:<T[urkey]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.github.coordinates2country.LibraryTest.testAllSamples(LibraryTest.java:39)
```
Thanks! :-)

**Comment by nicolas-raoul** [comment]
That error was with `openjdk 17.0.11 2024-04-16`.

How about removing the names from `countries.csv` and using the JDK's method in the unit tests? It would reduce maintenance and avoid future possible discrepancies/confusions. :-)

**Comment by ItzBubschki** [comment]
Fixed :)

**Review by nicolas-raoul — APPROVED** [review]

**Pull request merged**
